import { useNavigate } from 'react-router-dom';
import React from 'react';
import { Box, Typography } from '@mui/material';
import { alpha } from '@mui/material/styles';
import { SoftCard, GradientButton, SectionLabel } from '../components/shared';
import { COLORS } from '../theme/theme';

const sections = [
  { title: '1. Acceptance of Terms', body: 'By accessing or using Intervuew, you agree to be bound by these Terms of Service. If you do not agree, do not use the platform. These terms apply to all users including individual preppers and organisational accounts.' },
  { title: '2. Use of the Service', body: 'You may use Intervuew for lawful interview preparation and candidate assessment purposes only. You must not misuse the platform, attempt to reverse-engineer it, or use it to generate content that is discriminatory, illegal, or harmful.' },
  { title: '3. Accounts', body: 'You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. Notify us immediately at support@intervuew.ai if you suspect unauthorised access.' },
  { title: '4. Intellectual Property', body: 'Intervuew and its original content, features, and functionality are owned by Intervuew Ltd and are protected by international copyright, trademark, and other intellectual property laws. Your interview data remains your property.' },
  { title: '5. AI-Generated Content', body: 'Interview questions and evaluations are generated by AI. They are provided for informational and assessment purposes only and do not constitute professional HR, legal, or employment advice. Hiring decisions remain the sole responsibility of the employer.' },
  { title: '6. Payment & Billing', body: 'Paid plans are billed monthly or annually in advance. All fees are non-refundable except where required by law. We reserve the right to change pricing with 30 days notice. Downgrade or cancel anytime from your billing settings.' },
  { title: '7. Termination', body: "We may suspend or terminate your account immediately if you breach these Terms. You may terminate your account at any time. Upon termination, your right to use the Service ceases and your data is deleted per our Privacy Policy." },
  { title: '8. Limitation of Liability', body: 'To the fullest extent permitted by law, Intervuew shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the fees paid in the 12 months prior to the claim.' },
  { title: '9. Governing Law', body: 'These Terms are governed by the laws of England and Wales. Any disputes shall be resolved exclusively in the courts of London, UK, unless local consumer protection laws provide otherwise.' },
  { title: '10. Changes to Terms', body: 'We may update these Terms from time to time. We will notify you of material changes via email or in-app notification at least 14 days in advance. Continued use of the Service after changes constitutes acceptance.' },
];

const Terms: React.FC = () => {
  const nav = useNavigate();
  return (
  <Box sx={{ minHeight: '100vh', pt: '64px', background: COLORS.bg }}>
    <Box sx={{ maxWidth: 800, mx: 'auto', px: '48px', pt: '48px', pb: '72px' }}>
      <SectionLabel>Legal</SectionLabel>
      <Typography variant="h1" sx={{ fontSize: 'clamp(32px,4vw,50px)', mb: '12px' }}>Terms of Service</Typography>
      <Typography sx={{ fontSize: 14, color: COLORS.textMuted, mb: '48px' }}>Last updated: 1 March 2025 · Effective immediately</Typography>
      <Typography sx={{ fontSize: 16, lineHeight: 1.8, color: COLORS.textMuted, mb: '48px', p: '24px', borderRadius: '16px', background: alpha(COLORS.indigo, 0.04), border: `1px solid ${alpha(COLORS.indigo, 0.1)}` }}>
        Please read these Terms carefully before using Intervuew. They govern your use of our platform and services. For questions, contact us at <Box component="span" sx={{ color: COLORS.indigo, fontWeight: 500 }}>legal@intervuew.ai</Box>.
      </Typography>
      <Box sx={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
        {sections.map((s, i) => (
          <SoftCard key={i} sx={{ p: '28px 32px' }}>
            <Typography variant="h5" sx={{ fontSize: 17, mb: '10px' }}>{s.title}</Typography>
            <Typography sx={{ fontSize: 14, lineHeight: 1.8, color: COLORS.textMuted }}>{s.body}</Typography>
          </SoftCard>
        ))}
      </Box>
      <Box sx={{ mt: '48px', p: '24px', borderRadius: '16px', background: '#F3F4F6', textAlign: 'center' }}>
        <Typography sx={{ fontSize: 14, color: COLORS.textMuted, mb: '16px' }}>Need a custom DPA or enterprise agreement?</Typography>
        <GradientButton variant="ghost" onClick={() => nav('/contact')} sx={{ mx: 'auto' }}>Contact legal team</GradientButton>
      </Box>
    </Box>
  </Box>
);
}

export default Terms;
