import type { Job, Candidate, AnalyticsData } from '../types';

// applicationLink must be "/apply/<slug>" — the slug is what :jobSlug captures in the router.
// Test URLs on localhost:
//   http://localhost:5173/apply/senior-frontend-engineer-acme  → Senior Frontend Engineer
//   http://localhost:5173/apply/product-designer-acme          → Product Designer

export const mockJobs: Job[] = [
  {
    id: '1',
    title: 'Senior Frontend Engineer',
    company: 'Acme Corp',
    location: 'Remote',
    salary: '$120k – $160k',
    description: 'We are looking for a talented Senior Frontend Engineer to join our product team and help build world-class user experiences.',
    responsibilities: [
      'Build and maintain high-quality React applications',
      'Collaborate with design and product teams',
      'Mentor junior engineers',
      'Drive technical architecture decisions',
    ],
    qualifications: [
      '5+ years of frontend experience',
      'Strong TypeScript skills',
      'Experience with React ecosystem',
      'Understanding of web performance',
    ],
    questionMode: 'ai',
    applicationLink: '/apply/senior-frontend-engineer-acme',
    createdAt: '2024-01-15',
    applicants: 42,
    status: 'active',
  },
  {
    id: '2',
    title: 'Product Designer',
    company: 'Acme Corp',
    location: 'San Francisco, CA',
    salary: '$100k – $140k',
    description: 'Join our design team to craft beautiful, intuitive product experiences used by millions of people.',
    responsibilities: [
      'Design end-to-end product flows',
      'Create high-fidelity prototypes',
      'Conduct user research',
      'Maintain design system',
    ],
    qualifications: [
      '4+ years of product design',
      'Figma expert',
      'Strong portfolio',
      'Experience with design systems',
    ],
    questionMode: 'custom',
    questions: [
      'Walk me through your design process for a complex feature.',
      'How do you handle design feedback from stakeholders?',
      'Describe a time you advocated for the user.',
    ],
    applicationLink: '/apply/product-designer-acme',
    createdAt: '2024-01-20',
    applicants: 10,
    status: 'active',
  },
];

export const mockCandidates: Candidate[] = [
  {
    id: '1',
    name: 'Alex Johnson',
    email: 'alex@example.com',
    jobId: '1',
    jobTitle: 'Senior Frontend Engineer',
    cvScore: 87,
    interviewScore: 82,
    status: 'reviewed',
    appliedAt: '2024-01-22',
    strengths: ['Strong React skills', 'Excellent communication', 'Problem-solving'],
    weaknesses: ['Limited backend experience', 'Testing coverage'],
    skills: ['React', 'TypeScript', 'CSS', 'Node.js'],
    communication: 88,
    clarity: 84,
    technical: 79,
    confidence: 82,
    transcript: 'AI: Tell me about your experience with React...\nCandidate: I have been working with React for 6 years...',
  },
  {
    id: '2',
    name: 'Sarah Chen',
    email: 'sarah@example.com',
    jobId: '1',
    jobTitle: 'Senior Frontend Engineer',
    cvScore: 91,
    interviewScore: 88,
    status: 'interviewing',
    appliedAt: '2024-01-23',
    strengths: ['Deep TypeScript expertise', 'Performance optimization', 'Leadership'],
    weaknesses: ['Design sensibility', 'Stakeholder communication'],
    skills: ['TypeScript', 'React', 'GraphQL', 'Webpack'],
    communication: 85,
    clarity: 91,
    technical: 93,
    confidence: 87,
  },
  {
    id: '3',
    name: 'Marcus Williams',
    email: 'marcus@example.com',
    jobId: '2',
    jobTitle: 'Product Designer',
    cvScore: 78,
    interviewScore: 74,
    status: 'applied',
    appliedAt: '2024-01-24',
    strengths: ['Visual design', 'User research', 'Figma skills'],
    weaknesses: ['Data-driven decisions', 'Engineering collaboration'],
    skills: ['Figma', 'Sketch', 'Prototyping', 'User Research'],
    communication: 76,
    clarity: 72,
    technical: 68,
    confidence: 80,
  },
  {
    id: '4',
    name: 'Priya Sharma',
    email: 'priya@example.com',
    jobId: '1',
    jobTitle: 'Senior Frontend Engineer',
    cvScore: 94,
    interviewScore: 91,
    status: 'hired',
    appliedAt: '2024-01-18',
    strengths: ['Full-stack knowledge', 'System design', 'Communication'],
    weaknesses: ['Mobile experience'],
    skills: ['React', 'TypeScript', 'Node.js', 'AWS'],
    communication: 95,
    clarity: 92,
    technical: 90,
    confidence: 93,
  },
];

export const mockAnalytics: AnalyticsData = {
  totalApplications: 142,
  interviewsCompleted: 98,
  avgScore: 76,
  hireRate: 12,
  weeklyData: [
    { day: 'Mon', applications: 18, interviews: 12 },
    { day: 'Tue', applications: 24, interviews: 16 },
    { day: 'Wed', applications: 21, interviews: 18 },
    { day: 'Thu', applications: 31, interviews: 22 },
    { day: 'Fri', applications: 28, interviews: 19 },
    { day: 'Sat', applications: 12, interviews: 7 },
    { day: 'Sun', applications: 8, interviews: 4 },
  ],
};

export const prepperSessions = [
  { id: '1', role: 'Product Manager', date: '2024-01-22', score: 81, duration: '18m', status: 'completed' },
  { id: '2', role: 'Senior Engineer', date: '2024-01-20', score: 74, duration: '22m', status: 'completed' },
  { id: '3', role: 'Design Lead', date: '2024-01-18', score: 88, duration: '15m', status: 'completed' },
  { id: '4', role: 'Marketing Director', date: '2024-01-15', score: 69, duration: '20m', status: 'completed' },
];